-- phpMyAdmin SQL Dump
-- version 4.0.4.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Sep 30, 2015 at 05:57 PM
-- Server version: 5.5.32
-- PHP Version: 5.4.19

--
-- generated by
--  sammy mutisya.
--
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `tumhostel`
--
CREATE DATABASE IF NOT EXISTS `tumhostel` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `tumhostel`;

-- --------------------------------------------------------

--
-- Table structure for table `course`
--
-- Creation: Jun 01, 2015 at 04:54 AM
--

DROP TABLE IF EXISTS `course`;
CREATE TABLE IF NOT EXISTS `course` (
  `id` int(11) NOT NULL,
  `coursecode` varchar(30) NOT NULL,
  `coursename` varchar(30) NOT NULL,
  PRIMARY KEY (`coursecode`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `course`
--

INSERT INTO `course` (`id`, `coursecode`, `coursename`) VALUES
(0, 'BBA1', 'Business Adminstration'),
(0, 'J17S', 'Comp Science');

-- --------------------------------------------------------

--
-- Table structure for table `department`
--
-- Creation: Jun 02, 2015 at 09:43 PM
--

DROP TABLE IF EXISTS `department`;
CREATE TABLE IF NOT EXISTS `department` (
  `code` int(11) NOT NULL,
  `departmentname` varchar(50) NOT NULL,
  `schoolname` varchar(50) NOT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `department`
--

INSERT INTO `department` (`code`, `departmentname`, `schoolname`) VALUES
(2222, 'EEEE', 'Engineering and Technology'),
(3333, 'CIT', 'Engineering and Technology');

-- --------------------------------------------------------

--
-- Table structure for table `hostel`
--
-- Creation: Jun 01, 2015 at 05:31 AM
--

DROP TABLE IF EXISTS `hostel`;
CREATE TABLE IF NOT EXISTS `hostel` (
  `hostelid` int(11) NOT NULL,
  `hostelname` varchar(50) NOT NULL,
  `capacity` int(11) NOT NULL,
  `location` varchar(50) NOT NULL,
  `gender` set('male','female') NOT NULL,
  PRIMARY KEY (`hostelid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `hostel`
--

INSERT INTO `hostel` (`hostelid`, `hostelname`, `capacity`, `location`, `gender`) VALUES
(3214, 'kenyatta', 100, 'K.U', 'male'),
(3456, 'nyayo', 800, 'nw', 'female'),
(4321, 'mfumbiro', 400, 'sw', 'male'),
(5463, 'Nyayo _1', 5, 'K.U', 'female'),
(6666, 'Gonghills', 300, 'K.U', 'male'),
(6768, 'Nyayo _2', 800, 'Ruiru', 'male'),
(7878, 'Gonghills', 400, 'K.U', 'female');

-- --------------------------------------------------------

--
-- Table structure for table `registered`
--
-- Creation: Sep 03, 2015 at 06:25 AM
--

DROP TABLE IF EXISTS `registered`;
CREATE TABLE IF NOT EXISTS `registered` (
  `username` varchar(30) NOT NULL,
  `password` varchar(50) NOT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `registered`
--

INSERT INTO `registered` (`username`, `password`) VALUES
('', 'd41d8cd98f00b204e9800998ecf8427e'),
('student', 'student');

-- --------------------------------------------------------

--
-- Table structure for table `room`
--
-- Creation: Jun 01, 2015 at 05:34 AM
--

DROP TABLE IF EXISTS `room`;
CREATE TABLE IF NOT EXISTS `room` (
  `roomno` int(11) NOT NULL,
  `capacity` int(11) NOT NULL,
  `hostelname` varchar(50) NOT NULL,
  PRIMARY KEY (`roomno`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `room`
--

INSERT INTO `room` (`roomno`, `capacity`, `hostelname`) VALUES
(44, 3, 'Nyayo _1'),
(1212, 3, 'Gonghills'),
(3333, 4, 'nyayo'),
(4321, 4, 'mfumbiro'),
(4444, 2, 'Gonghills'),
(5555, 4, 'kenyatta'),
(5656, 3, 'Nyayo _2');

-- --------------------------------------------------------

--
-- Table structure for table `room_alloc`
--
-- Creation: Jun 03, 2015 at 06:09 AM
--

DROP TABLE IF EXISTS `room_alloc`;
CREATE TABLE IF NOT EXISTS `room_alloc` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `student` varchar(50) NOT NULL,
  `hname` varchar(50) NOT NULL,
  `semester` int(11) NOT NULL,
  `year` varchar(20) NOT NULL,
  `room` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `room` (`room`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=41 ;

--
-- Dumping data for table `room_alloc`
--

INSERT INTO `room_alloc` (`id`, `student`, `hname`, `semester`, `year`, `room`) VALUES
(1, '6666', 'nyayo', 1, '2014/2015', 3333),
(2, '9999', 'mfumbiro', 1, '2014/2015', 0),
(3, '9999', 'nyayo', 1, '2014/2015', 0),
(4, '9999', 'nyayo', 1, '2014/2015', 0),
(5, '9999', 'mfumbiro', 1, '2014/2015', 0),
(6, '9999', 'nyayo', 1, '2014/2015', 0),
(7, '6666', 'kenyatta', 1, '2014/2015', 0),
(8, 'J17S/msa', 'kenyatta', 1, '2014/2015', 0),
(9, 'j17s/msa', 'kenyatta', 1, '2014/2015', 0),
(10, '7685', 'kenyatta', 1, '2014/2015', 0),
(11, '985746', 'Gonghills', 1, '2014/2015', 0),
(12, 'j17s/msa', 'kenyatta', 1, '2014/2015', 0),
(13, 'J18s/msa', 'kenyatta', 1, '2014/2015', 0),
(14, '3333', 'kenyatta', 1, '2014/2015', 0),
(15, '6666', 'kenyatta', 1, '2014/2015', 0),
(17, '6767', 'mfumbiro', 3, '2014/2015', 3434),
(18, '6767', 'mfumbiro', 3, '2014/2015', 3434),
(19, '6767', 'mfumbiro', 3, '2014/2015', 3434),
(20, '6767', 'mfumbiro', 3, '2014/2015', 3434),
(21, '4444', 'mfumbiro', 3, '2014/2015', 6666),
(22, '6666', 'kenyatta', 1, '2014/2015', 0),
(23, 'j17s/msa', 'kenyatta', 1, '2014/2015', 0),
(24, 'j18s/msa', 'kenyatta ', 1, '2014/2015 ', 0),
(25, '6666', 'kenyatta ', 1, '2014/2015 ', 0),
(26, '6666', 'kenyatta ', 1, '2014/2015 ', 0),
(27, '7890', 'Nyayo_2 ', 2, '2014/2015 ', 456),
(28, '6666', 'kenyatta ', 1, '2014/2015 ', 0),
(29, '6666', 'kenyatta ', 1, '2014/2015 ', 0),
(31, '6666', 'kenyatta ', 1, '2014/2015 ', 0),
(32, '6666', 'kenyatta ', 2, '2015/2016 ', 0),
(33, 'j17s/msa', 'kenyatta ', 2, '2015/2016 ', 0),
(34, 'j18s/msa', 'kenyatta ', 3, '2014/2015 ', 0),
(35, 'MEEH', 'kenyatta ', 2, '2015/2016 ', 0),
(36, 'EEEE/9090', 'kenyatta ', 2, '2015/2016 ', 0),
(37, 'BBA2010', 'kenyatta ', 2, '2015/2016 ', 0),
(38, 'j17s/msa', 'kenyatta ', 2, '2015/2016 ', 0),
(39, 'hh2333', 'kenyatta ', 2, '2015/2016 ', 0),
(40, 'j17s/msa', 'nyayo ', 2, '2015/2016 ', 0);

-- --------------------------------------------------------

--
-- Table structure for table `school`
--
-- Creation: Jun 01, 2015 at 05:45 AM
--

DROP TABLE IF EXISTS `school`;
CREATE TABLE IF NOT EXISTS `school` (
  `id` int(11) NOT NULL,
  `schoolname` varchar(50) NOT NULL,
  `departments` set('CIT','EEE','MECH','ENERGY') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `school`
--

INSERT INTO `school` (`id`, `schoolname`, `departments`) VALUES
(2222, 'Enginering', 'CIT'),
(4432, 'economic', 'EEE');

-- --------------------------------------------------------

--
-- Table structure for table `session`
--
-- Creation: Jun 02, 2015 at 10:23 PM
--

DROP TABLE IF EXISTS `session`;
CREATE TABLE IF NOT EXISTS `session` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `year` varchar(20) NOT NULL,
  `sem` enum('1','2','3') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=7 ;

--
-- Dumping data for table `session`
--

INSERT INTO `session` (`id`, `year`, `sem`) VALUES
(6, '2015/2016', '2');

-- --------------------------------------------------------

--
-- Table structure for table `signup`
--
-- Creation: Sep 05, 2015 at 06:10 PM
--

DROP TABLE IF EXISTS `signup`;
CREATE TABLE IF NOT EXISTS `signup` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=16 ;

--
-- Dumping data for table `signup`
--

INSERT INTO `signup` (`id`, `username`, `password`) VALUES
(10, 'sammy', 'd41d8cd98f00b204e9800998ecf8427e'),
(11, 'mulewa', 'd41d8cd98f00b204e9800998ecf8427e'),
(12, 'kalomo', 'd41d8cd98f00b204e9800998ecf8427e'),
(13, 'molutu', ''),
(14, 'sybl', 'd41d8cd98f00b204e9800998ecf8427e'),
(15, 'kivaki', 'd41d8cd98f00b204e9800998ecf8427e');

-- --------------------------------------------------------

--
-- Table structure for table `student`
--
-- Creation: Jun 01, 2015 at 05:03 AM
--

DROP TABLE IF EXISTS `student`;
CREATE TABLE IF NOT EXISTS `student` (
  `studentid` varchar(20) NOT NULL,
  `fname` text NOT NULL,
  `lname` text NOT NULL,
  `course` varchar(50) NOT NULL,
  `gender` set('male','female') NOT NULL,
  `mobile` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `status` set('on','off') NOT NULL,
  PRIMARY KEY (`studentid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `student`
--

INSERT INTO `student` (`studentid`, `fname`, `lname`, `course`, `gender`, `mobile`, `email`, `status`) VALUES
('1234', 'kingoo', 'munuve', 'J17S, Comp Science', 'male', '986875664', 'bridgit@yahoo.com', 'on'),
('23455', 'Abednego', 'Mukwekwe', 'BBA1, Business Adminstration', 'male', '07283456728', 'abed@yahoo.com', ''),
('3333', 'Charity ', 'Sybl', 'BBA1, Business Adminstration', 'female', '25437899758', 'mtisyas@yahoo.com', ''),
('6666', 'kivaki', 'bridgit', 'BBA1, Business Adminstration', 'female', '986875664', 'kivaki@yahoo.com', ''),
('BBA2010', 'Kathule ', 'Mutisya', 'BBA1, Business Adminstration', 'female', '07143256789', 'kathule@gmail', ''),
('Bcom 2211', 'muthoka', 'maundu', 'BBA1, Business Adminstration', 'male', '8877665533', 'muthoka@yahoo.com', ''),
('EEEE/5678', 'Ezekiel', 'Mumanyi', 'J17S, Comp Science', 'male', '072345178905', 'ezeky@yahoo.com', ''),
('EEEE/9090', 'Lauh', 'mulalya', 'BBA1, Business Adminstration', 'male', '09874653', 'Yusuf@gmail.com', ''),
('EH560', 'singi', 'norris', 'electrical', 'male', '34526719', 'norris@yahoo.com', 'on'),
('H1234', 'Ruth', 'Jepcheng', 'BBA1, Business Adminstration', 'male', '0711223344', 'ruth@yahoo.com', ''),
('HH2313', 'Bridgit', 'Mutanu', 'BBA1, Business Adminstration', 'female', '07892777289', 'bridgit@yahoo.com', ''),
('HH2324', 'Mwikali', 'Kimba', 'BBA1, Business Adminstration', 'female', '087957648', 'Mwika@gmail.com', ''),
('HH2333', 'Muthike', 'Kituu', 'J17S, Comp Science', 'female', '0798645332', 'Kituu@gmiasl.com', 'off'),
('J16S/MSA', 'Tombias', 'Obiero', 'J17S, Comp Science', 'male', '07546738920', 'tombi@yahoo.com', ''),
('J17S/MSA', 'Bryan', 'kithoi', 'J17S, Comp Science', 'male', '986875664', 'mtisyas@yahoo.com', ''),
('J18S/MSA', 'Bryan', 'kithoi', 'J17S, Comp Science', 'male', '0724795773', 'samtish2010@gmail.com', ''),
('kk9089', 'Joseph', 'Moki', 'BBA1, Business Adminstration', 'male', '0987566455', 'moki@mail.com', 'on'),
('kk9090', 'monika', 'makau', 'J17S, Comp Science', 'female', '986875664', 'sbyl@yahoo.com', ''),
('MEEH', 'Michael', 'Sammy', 'J17S, Comp Science', 'male', '89488553552', 'micahel@yahoo.com', ''),
('nzbni', 'moses', 'maluki', 'BBA1, Business Adminstration', 'male', '098765432', 'mosex@sam.com', ''),
('wwww', 'Conny', 'Maina', 'Beauty', 'female', '', '', 'off');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--
-- Creation: Sep 03, 2015 at 07:27 AM
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user` (`username`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=12 ;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `password`) VALUES
(1, '', 'd41d8cd98f00b204e9800998ecf8427e'),
(9, 'student', 'password'),
(10, 'sammy', '1234'),
(11, 'admin', 'pass');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
